In [17]:
# import libraries
import numpy as np
import pandas as pd
import re

In [49]:
# read raw file
db = pd.read_csv('../data/raw/avg_rent_month.csv')

In [50]:
db.info()
db.head()

<class 'pandas.DataFrame'>
RangeIndex: 326 entries, 0 to 325
Data columns (total 31 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Month                              326 non-null    str
 1   Class A Hong Kong                  326 non-null    int64
 2   Class A Hong Kong - Remarks        3 non-null      str
 3   Class A Kowloon                    326 non-null    int64
 4   Class A Kowloon - Remarks          3 non-null      str
 5   Class A New Territories            326 non-null    int64
 6   Class A New Territories - Remarks  3 non-null      str
 7   Class B Hong Kong                  326 non-null    int64
 8   Class B Hong Kong - Remarks        3 non-null      str
 9   Class B Kowloon                    326 non-null    int64
 10  Class B Kowloon - Remarks          3 non-null      str
 11  Class B New Territories            326 non-null    int64
 12  Class B New Territories - Remarks  3 non-null      str
 13  Class C Hong Kong                  326 non-null    int64
 14  Class C Hong Kong - Remarks        9 non-null      str
 15  Class C Kowloon                    326 non-null    int64
 16  Class C Kowloon - Remarks          13 non-null     str
 17  Class C New Territories            326 non-null    int64
 18  Class C New Territories - Remarks  9 non-null      str
 19  Class D Hong Kong                  326 non-null    int64
 20  Class D Hong Kong - Remarks        13 non-null     str
 21  Class D Kowloon                    326 non-null    int64
 22  Class D Kowloon - Remarks          40 non-null     str
 23  Class D New Territories            326 non-null    int64
 24  Class D New Territories - Remarks  17 non-null     str
 25  Class E Hong Kong                  326 non-null    int64
 26  Class E Hong Kong - Remarks        12 non-null     str
 27  Class E Kowloon                    326 non-null    str
 28  Class E Kowloon - Remarks          320 non-null    str
 29  Class E New Territories            326 non-null    str
 30  Class E New Territories - Remarks  146 non-null    str
dtypes: int64(13), str(18)
memory usage: 79.1 KB

,Month,Class A Hong Kong,Class A Hong Kong - Remarks,Class A Kowloon,Class A Kowloon - Remarks,Class A New Territories,Class A New Territories - Remarks,Class B Hong Kong,Class B Hong Kong - Remarks,Class B Kowloon,...,Class D Kowloon,Class D Kowloon - Remarks,Class D New Territories,Class D New Territories - Remarks,Class E Hong Kong,Class E Hong Kong - Remarks,Class E Kowloon,Class E Kowloon - Remarks,Class E New Territories,Class E New Territories - Remarks
0,Jan-99,190,NaN,171,NaN,133,NaN,199,NaN,165,...,198,NaN,185,NaN,301,NaN,185,NaN,191,NaN
1,Feb-99,196,NaN,173,NaN,133,NaN,204,NaN,165,...,196,Z,173,NaN,311,NaN,213,Z,152,NaN
2,Mar-99,199,NaN,170,NaN,133,NaN,197,NaN,160,...,174,NaN,186,NaN,301,NaN,194,Z,190,Z
3,Apr-99,191,NaN,171,NaN,135,NaN,200,NaN,156,...,172,NaN,170,NaN,313,NaN,221,Z,172,NaN
4,May-99,191,NaN,175,NaN,127,NaN,188,NaN,155,...,180,NaN,180,NaN,289,NaN,168,Z,162,Z

Remarks:
1. Delete all the Remarks columns.

In [51]:
# find all the remarks columns
remark_cols = [col for col in db.columns if re.search(r'Remarks', col, re.IGNORECASE)]

# drop the remarks columns
db.drop(columns=remark_cols, inplace=True)

In [52]:
db.head()

,Month,Class A Hong Kong,Class A Kowloon,Class A New Territories,Class B Hong Kong,Class B Kowloon,Class B New Territories,Class C Hong Kong,Class C Kowloon,Class C New Territories,Class D Hong Kong,Class D Kowloon,Class D New Territories,Class E Hong Kong,Class E Kowloon,Class E New Territories
0,Jan-99,190,171,133,199,165,118,249,187,150,284,198,185,301,185,191
1,Feb-99,196,173,133,204,165,114,239,177,144,268,196,173,311,213,152
2,Mar-99,199,170,133,197,160,117,247,177,142,262,174,186,301,194,190
3,Apr-99,191,171,135,200,156,116,256,182,134,279,172,170,313,221,172
4,May-99,191,175,127,188,155,113,233,175,133,279,180,180,289,168,162

Remarks:
1. The information of Dec-25, Jan-26, Feb-26 are provisional.
2. Only analysis Nov-24 to Nov-25 data.

In [53]:
# Change Month column to datetime format
db['Month'] = pd.to_datetime(db['Month'], format='%b-%y')

# Delete row excluding the period Nov-24 to Oct-25
db = db[(db['Month'] >= pd.to_datetime('Nov-24', format='%b-%y')) & (db['Month'] <= pd.to_datetime('Oct-25', format='%b-%y'))]

# Format Month column to MM-YY string format
db['Month'] = db['Month'].dt.strftime('%m-%y')

In [56]:
db.head(12)

,Month,Class A Hong Kong,Class A Kowloon,Class A New Territories,Class B Hong Kong,Class B Kowloon,Class B New Territories,Class C Hong Kong,Class C Kowloon,Class C New Territories,Class D Hong Kong,Class D Kowloon,Class D New Territories,Class E Hong Kong,Class E Kowloon,Class E New Territories
310,11-24,479,444,329,407,366,275,419,384,273,425,362,242,460,335,209
311,12-24,475,424,331,401,368,278,419,379,280,429,369,259,442,350,202
312,01-25,488,419,339,397,360,278,434,356,274,437,343,242,432,448,222
313,02-25,477,433,336,406,359,277,427,392,279,429,371,256,490,340,239
314,03-25,476,427,341,397,365,276,429,362,280,431,364,257,465,382,190
315,04-25,469,415,337,406,363,278,434,368,281,421,353,243,451,424,207
316,05-25,494,433,341,403,372,276,429,379,284,435,367,225,466,287,230
317,06-25,499,429,337,417,366,278,443,398,271,431,379,259,454,335,217
318,07-25,503,432,346,408,366,282,440,404,282,451,392,249,430,309,229
319,08-25,516,467,368,411,384,290,421,398,283,429,374,254,445,423,242
320,09-25,502,467,338,415,380,282,439,402,280,466,384,232,450,540,219
321,10-25,490,449,337,432,377,281,435,399,278,459,359,241,480,492,225

In [57]:
# save changes to cleaned file
db.to_csv('../data/cleaned/avg_rent_month_cleaned.csv', index=False)